config/routes.rb
Rails.application.routes.draw do
  get 'news/favs', to: 'news#favs'
  devise_for :users
  resources :news do
    member do
      post :add_comment
      post :delete_comment
      post :like
      post :favorite_add
    end
  end
  resources :user_profile do
    member do
      post :change_subscr_period
      post :change_user_name
      post :change_user_email
      post :upload_file
      get :subscribe
      post :unsubscribe
      get :subscribes
      get :user_settings
      get :posts
    end
  end
  root to: 'news#index'
  post 'user_profile/unsubscribe_all', to: "user_profile#unsubscribe_all"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/news.rb
class News < ApplicationRecord
    belongs_to :user
    has_one_attached :image
    has_many :comments
    has_many :likes
    self.per_page = 5
end

app/controllers/news_controller.rb
# frozen_string_literal: true

class NewsController < ApplicationController
  include NewsHelper
  before_action :authenticate_user!
  before_action :set_news, only: [:show, :edit, :update, :destroy, :add_comment, :like, :favorite_add]
  before_action :check_user_only, only: [:index]

  add_flash_types :danger
  add_flash_types :success

  # GET /news
  # GET /news.json
  def index
    if @only_my
      @news = News.joins("LEFT JOIN users
        ON users.id = news.user_id
        LEFT JOIN subscribes
        ON subscribes.user_id = #{current_user.id}
        ").where('subscribes.s_user_id = news.user_id').paginate(page: params[:page]).order(created_at: :desc)
    else
      @news = News.all.paginate(page: params[:page]).order(created_at: :desc)
    end
  end

  # GET /news/1
  # GET /news/1.json
  def show; end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit; end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)
    @news.DateTime = Time.now.asctime
    @news.user_id = current_user.id
    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, success: 'Запись успешно обновлена.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, success: 'Запись успешно обновлена.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, success: 'Запись успешно удалена.' }
      format.json { head :no_content }
    end
  end

  def add_comment
    @comment = @news.comments.create!([{ user_id: current_user.id, text: params[:text] }])
    redirect_to news_path(@news), success: 'Комментарий добавлен.'
  end

  def delete_comment
    @comment = Comment.find(params[:comment_id])
    if @comment.destroy
      redirect_back fallback_location: :back, success: 'Комментарий удален.'
    end
  end

  def like
    respond_to do |format|
      user_like = check_like(@news)
      if user_like
        if user_like.destroy
          @img = ActionController::Base.helpers.asset_path('svg/heart-regular.svg')
          format.json { render json: { likes: @news.likes.count, img: @img }, status: :ok }
        else
          format.json { render json: @like.errors, status: :unprocessable_entity }
        end
      else
        @like = Like.new(user_id: current_user.id, news_id: @news.id)
        if @like.save
          @img = ActionController::Base.helpers.asset_path('svg/heart-solid.svg')
          format.json { render json: { likes: @news.likes.count, img: @img }, status: :ok }
        else
          format.json { render json: @like.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def favs
    @news = News.joins("LEFT JOIN favorites ON favorites.news_id = news.id").where("news.id = favorites.news_id and favorites.user_id = #{current_user.id}")
    respond_to do |format|
      format.html {render :'news/favorites'}
    end
  end

  def favorite_add
    respond_to do |format|
      user_favorite = check_favorite(@news)
      if user_favorite
        if user_favorite.destroy
          @img = ActionController::Base.helpers.asset_path('svg/star-regular.svg')
          format.json {render json: {img: @img, result: "deleted"}, status: :ok}
        else
          format.json {render json: user_favorite.errors, status: :unprocessable_entity}
        end
      else
        @fav = Favorite.new(user_id: current_user.id, news_id: @news.id)
        if @fav.save
          @img = ActionController::Base.helpers.asset_path('svg/star-solid.svg')
          format.json {render json: {img: @img, result: "added"}, status: :ok}
        else
          format.json {render json: @fav.errors, status: :unprocessable_entity}
        end
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_news
    @news = News.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def news_params
    params.require(:news).permit(:title, :text, :image, :only_my)
  end

  def check_user_only
    @only_my = params[:only_my]
  end
end

app/helpers/news_helper.rb
module NewsHelper
  def check_like(news)
    @user_like = Like.left_joins(:user, :news).where(users: {id: current_user.id}, news: {id: news.id}).take
  end

  def check_favorite(news)
    @user_favorite = Favorite.left_joins(:user, :news).where(users: {id: current_user.id}, news: {id: news.id}).take
  end
end

app/views/news/_comments.html.slim
br
div.container
  div.row
    div.col
      h4 Комментарии: #{@news.comments.count}
    div.col style="text-align:right"
      a class="btn btn-outline-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample" Написать
  hr.my-4
  div.row
    div.col
      div class="collapse" id="collapseExample"
        = form_with(url: add_comment_news_path(@news), method:"post") do |f|
          / = f.label :"Текст комментария", for:"FormInput"
          = f.text_area :text, id:"FormInput", class:"form-control", placeholder:"Введите текст комментария", "aria-describedby": "formHelp"
          br
          = f.submit value: "Добавить", class: "btn btn-outline-primary"
          hr.my-4
  - @news.comments.all.order(created_at: :desc).each do |comment|
    p
      = image_tag(comment.user.image.variant(resize: "32x32"), :class=> "rounded-circle")
      span.lead style="padding-left:8px" = link_to comment.user.name, user_profile_path(comment.user)
      -if comment.user.id == current_user.id || @news.user.id == current_user.id
        = link_to( delete_comment_news_path(comment_id: comment.id), :role => "button", :class=>"close", :method=> "POST") do
          span aria-hidden="true"&times;
    p.lead = comment.text
    hr.my-4

javascript:
  $('#collapseExample').on('shown.bs.collapse', function () {
      $('html, body').animate({
          scrollTop: $('div.collapse').offset().top + $('form').height()
      }, 'fast');
      $('#FormInput').focus();
  }).on('hidden.bs.collapse', function () {
     $('#FormInput').blur();
  });

app/views/news/_form.html.slim
= form_for @news do |f|
  - if @news.errors.any?
    #error_explanation
      h2 = "#{pluralize(@news.errors.count, "error")} prohibited this news from being saved:"
      ul
        - @news.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :Название
    = f.text_field :title, class: "form-control"
  .field
    = f.label :Содержимое
    = f.text_area :text, class: "form-control", rows:"10"
  div class="custom-file"
    .field
      = f.label :Изображение, class:"custom-file-label", for:"customFile", id:"filename"
      = f.file_field :image, class: "custom-file-input", id:"customFile", onchange:"fileInputChangeSingle(this)"
  div id="img-preview"
  br
  .actions = f.submit value: "Сохранить запись", class: "btn btn-success"

app/views/news/edit.html.slim
h1 Изменить запись

== render 'form'

=> link_to 'Просмотр', @news,  class: "btn btn-outline-dark", role: "button"
'|
=< link_to 'Назад', :back, class: "btn btn-outline-dark", role: "button"

app/views/news/favorites.html.slim
- @news.all.each do |news|
  == render partial: 'layouts/post', locals: {news: news}

app/views/news/index.html.slim
h2 = link_to 'Новая Запись', new_news_path, class: "btn btn-outline-primary", role: "button", id: "AddButton"
h1 = @user_news  
- @news.each do |news|
    = render partial: 'layouts/post', locals: {news: news}
div style="display:flex"
  div style="margin:auto"
    = will_paginate @news, renderer: WillPaginate::ActionView::BootstrapLinkRenderer

app/views/news/new.html.slim
h1 Создать запись

== render 'form'

= link_to 'Назад', :back, class: "btn btn-outline-dark", role: "button"

app/views/news/show.html.slim
div class="jumbotron jumbotron-fluid news-box rounded shadow-sm"
  div class="container"
    div style="display:flex"
      h2 class="display-8"
        = @news.title
      = image_tag(@news.user.image, :class=> "avatar", :style => "width:32px; height:32px;margin-left:auto;margin-right:5px;border-radius:50%;align-self:center") if @news.user.image.attached?
      h2 class="display-10" style="align-self:center; #{"margin-left:auto" unless @news.user.image.attached?}"
        - if @news.user.id == current_user.id
          = link_to @news.user.name, user_profile_index_path
        - else
          = link_to @news.user.name, user_profile_path(@news.user)
    hr class="my-4"
    p class="lead"
      = @news.text
    div style="display:flex"
      = image_tag @news.image.variant(resize: '500x500'), :class => "img-fluid", style:"margin:auto" if @news.image.attached?
    hr class="my-4"
    - if current_user.id == @news.user.id
      => link_to 'Изменить', edit_news_path(@news), class: "btn btn-outline-dark", role: "button"
      '|
      => link_to "Удалить", news_path(@news), class: "btn btn-outline-dark", role: "button", method:"DELETE", data: { confirm: 'Вы уверены что хотите удалить запись??' }
      '|
      =< link_to 'Назад', :back, class: "btn btn-outline-dark", role: "button"

== render 'comments'