config/routes.rb
Rails.application.routes.draw do
  get 'news/favs', to: 'news#favs'
  devise_for :users
  resources :news do
    member do
      post :add_comment
      post :delete_comment
      post :like
      post :favorite_add
    end
  end
  resources :user_profile do
    member do
      post :change_subscr_period
      post :change_user_name
      post :change_user_email
      post :upload_file
      get :subscribe
      post :unsubscribe
      get :subscribes
      get :user_settings
      get :posts
    end
  end
  root to: 'news#index'
  post 'user_profile/unsubscribe_all', to: "user_profile#unsubscribe_all"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/user_profile_controller.rb
class UserProfileController < ApplicationController
  before_action :authenticate_user!
  before_action :subscribes_count
  before_action :posts_count
  before_action :set_types, only: :user_settings

  add_flash_types :danger
  add_flash_types :success

  def index
    redirect_to user_profile_path(current_user)
  end

  def show
    @user = set_user
  end

  def change_subscr_period
    @subscr = Subscribe.find(params[:id])
    @subscr.schedule_interval_days = params[:period]
    if @subscr.save
      redirect_to user_profile_index_path, success: 'Период рассылки изменен'
    else
      redirect_to user_profile_index_path, danger: 'Ошибка при изменение периода рассылки'
    end
  end

  def upload_file
    current_user.image = params[:image]
    if current_user.save
      redirect_to user_profile_path(current_user), success: 'Фото профиля обновлено'
    else
      redirect_to user_profile_path(current_user), danger: 'Ошибка при обновлении профиля'
    end
  end

  def update
    current_user.update(user_params)
    if current_user.save
      redirect_to user_profile_path(current_user), success: 'Настройки профиля сохранены'
    elsif current_user.errors.any?
      errors = ''
      current_user.errors.full_messages.each do |msg|
        errors << msg
      end
      redirect_to user_profile_path(current_user), danger: "Ошибка #{errors}"
    else
      redirect_to user_profile_path(current_user), danger: 'Ошибка: Что то пошло не так}'
    end
  end

  def subscribe
    @user = set_user
    @subscr = Subscribe.new(user_id: current_user.id, s_user_id: @user.id, schedule_interval_days: 1, active: true)
    if @subscr.save
      redirect_back fallback_location: :back, success: "Вы подписались на пользователя #{@user.name}"
    else
      redirect_back fallback_location: :back, danger: "Что то пошло не так #{@subscr.errors}"
    end
    end

  def unsubscribe
    @subscr = Subscribe.where(user_id: current_user.id, id: params[:id])
    @subscr.destroy
    redirect_back fallback_location: :back, success: 'Вы отписались.'
  end

  def unsubscribe_all
    current_user.subscribes.destroy_all
    redirect_back fallback_location: :back, success: 'Вы отписались от всех подписок'
  end

  def subscribes_count
    @subscr_cnt = current_user.subscribes.count
  end

  def posts; end

  def subscribes; end

  def user_settings; end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.permit(:name, :lastname, :email, :image, :mail_interval_id, :subscribe_type_id, :about)
  end

  def posts_count
    @posts_cnt = current_user.news.count
  end

  def set_types
    @_types = SubscribeType.all
    @intevals = MailInterval.all
  end
end

app/helpers/user_profile_helper.rb
module UserProfileHelper
end

app/views/user_profile/_posts.html.slim
- if @posts_cnt == 0
  br
  p style="color:gray; text-align:center" Вы еще не написали ни одного поста
  hr class="my-4"
- current_user.news.all.order(created_at: :desc).each do |news|
  div class="jumbotron jumbotron-fluid rounded shadow-sm news-box"
    div class="container"
      div style="display:flex" 
        h3 class="display-8" = link_to news.title, news
        = image_tag(news.user.image.variant(resize:"32x32"), :class=> "avatar", :style => "width:32px; height:32px;margin-left:auto;margin-right:5px;border-radius:50%") if news.user.image.attached?
        h3 class="display-8" style='#{"margin-left:auto" if !news.user.image.attached?}' 
         - if news.user.id != current_user.id
          = link_to news.user.name, user_profile_path(news.user.id)
         - else
          = link_to news.user.name, user_profile_index_path
      p = time_ago_in_words(news.created_at)
      hr class="my-4"
      p class="lead" #{truncate news.text, length: 350} #{link_to 'Далее', news, style:"color:blue" if news.text.length > 350}

app/views/user_profile/_subscribes.html.slim
br
- if @subscr_cnt == 0
  p style="color:gray; text-align:center" Вы еще ни на кого не подписались
table style="max-widtsh:50%" class="table"
  /thead class="thead-dark"
    tr
      /th scope="col" Пользователь
      /th scope="col" Период рассылки в днях
      /th style="text-align:right" scope="col" Отписаться
  tbody
    - current_user.subscribes.all.order(created_at: :desc).each do |subscribe|
     tr
      /th scope="row"
      th scope="row" 
        - @s_user = User.find(subscribe.s_user_id)
        = image_tag @s_user.image.variant(resize: "64x64"), class: "rounded-circle d-inline" if @s_user.image.attached?
        h3 class="d-inline" = link_to @s_user.name, user_profile_path(@s_user), style: "padding:0 0 0 8px"
      / td
      /     = form_with(url: change_subscr_period_user_profile_path(subscribe), method:"post") do |f|
      /       div class="input-group mb-3"
      /         = f.text_field :period, value: subscribe.schedule_interval_days, class:"form-control", "aria-describedby":"button-addon2", style:"width:30px; max-width:50px"
      /         div class="input-group-append"
      /           = f.submit value:"Сохранить", class:"btn btn-outline-success", id:"button-addon2"
      td style="vertical-align:middle" align="right" = link_to "Отписаться", unsubscribe_user_profile_path(subscribe), method: :post, class:"btn btn-outline-danger", role:"button"
    td
    td align="right" = link_to "Отписаться от всех", user_profile_unsubscribe_all_path,  method: :post, class:"btn btn-outline-danger", role:"button" if @subscr_cnt > 0

app/views/user_profile/_user_settings.html.slim
br
div
 = form_with(url:user_profile_path(current_user), method:"put") do |f|
    label for="InputName" Имя
    div class="input-group mb-3" id="InputName"
     = f.text_field :name, placeholder: "Имя пользователя", class:"form-control", "aria-describedby":"button-addon2", value: current_user.name
    label for="InputName" Фамилия
    div class="input-group mb-3" id="InputLastName"
     = f.text_field :lastname, placeholder: "Фамилия", class:"form-control", "aria-describedby":"button-addon2", value: "#{current_user.lastname if current_user.lastname}"
    label for="InputEmail" Электронная почта
    div class="input-group mb-3" id="InputEmail"
     = f.text_field :email, placeholder: "Электронная почта", class:"form-control", "aria-describedby":"button-addon2", value: current_user.email
    label for="InputAbout" О себе
    div class="input-group mb-3" id="InputAbout"
     = f.text_area :about, placeholder: "Расскажите немного о себе", class:"form-control", "aria-describedby":"button-addon2", value: current_user.about, maxlength: "400"
    label for="FormGroupSelect" Настройка почтовой рассылки
    div class="input-group" id="FormGroupSelect"
        = f.select :mail_interval_id, options_for_select(mail_intervals, current_user.mail_interval.id), {}, {class: "form-control", id: "exampleFormControlSelect1"}        
        = f.select :subscribe_type_id, options_for_select(subscribe_types, current_user.subscribe_type.id), {}, {class: "form-control", id: "exampleFormControlSelect1"}
        div class="input-group-append"
            span class="input-group-text" Период
            span class="input-group-text" Тип
    br
    = f.submit value: "Сохранить", class: "btn btn-outline-success"
 = form_with(url:upload_file_user_profile_path(current_user), method:"post", id:"photo-form") do |f|
    br
    div id="img-preview"
        - if current_user.image.attached?
            = image_tag current_user.image.variant(resize: "250x250"), class:"img-thumbnail", id:"preview"
        - else
            = image_tag 'user_default.png', class:"img-thumbnail", style: "width:250px;heigth:250px", id:"preview" 
    label for="ChosePicture" Выбрать изображение профиля
    div class="custom-file"
        = f.label :Изображения, class:"custom-file-label", for:"customFile", id:"filename"
        = f.file_field :image, class: "custom-file-input", id:"customFile", onchange:"fileInputChangeSingle(this, '250px', '250px', true)"
        = f.button :"Сохранить", class:"btn btn-outline-success", type: "button", onclick: "SendCropped(this)"    

app/views/user_profile/index.html.slim
br
ul class="nav nav-tabs" id="nav-tab" role="tablist"
  li class="nav-item"
    a class="nav-link active" id="posts-tab" data-toggle="tab" href="#posts" role="tab" aria-controls="posts" aria-selected="true" Посты
  li class="nav-item"
    a class="nav-link" id="subscribes-tab" data-toggle="tab" href="#subscribes" role="tab" aria-controls="subscribes" aria-selected="false" Подписки
  li class="nav-item"
    a class="nav-link" id="settings-tab" data-toggle="tab" href="#settings" role="tab" aria-controls="settings" aria-selected="false" Настройки
    
div class="tab-content" id="myTabContent"
  div class="tab-pane fade" id="subscribes" role="tabpanel" aria-labelledby="subscribes-tab" == render template 'subscribes'
  div class="tab-pane fade" id="settings" role="tabpanel" aria-labelledby="settings-tab" == render 'user_settings'
  div class="tab-pane fade show active" id="posts" role="tabpanel" aria-labelledby="posts-tab" == render 'posts'
javascript:
  $(document).ready(function(){
    var savedTab = localStorage.getItem('savedTab');
    if(!!savedTab){
        $(`a[href="${savedTab}"]`).tab('show');
    }
    var s = $('a[data-toggle="tab"]');
    s.on("shown.bs.tab", function(e){
        var href = e.target.href;
        href = href.substring(href.lastIndexOf("#"));
        history.pushState(null, null, href);
        localStorage.setItem('savedTab', href);
    })
  })

app/views/user_profile/posts.html.slim
- if @posts_cnt == 0
  br
  p style="color:gray; text-align:center" Вы еще не написали ни одного поста
  hr class="my-4"
- current_user.news.all.order(created_at: :desc).each do |news|
  = render partial: 'layouts/post', locals: {news: news}

app/views/user_profile/show.html.slim
br
div.row
  div.col-3
    = image_tag @user.image.variant(resize: "250x250"), class:"img-thumbnail" if @user.image.attached?
  div.col-9 style="padding-left:8px;overflow:auto"
    h2 = @user.name
    -if current_user.id == @user.id
      = link_to "Настройки", user_settings_user_profile_path(current_user), role:"button", class: "btn btn-outline-primary"
    - else
      - if !current_user.subscribes.where(:s_user_id => @user.id).take
        = link_to "Подписаться", subscribe_user_profile_path(@user), role:"button", class: "btn btn-outline-primary"
      - else
        = link_to "Отписаться", unsubscribe_user_profile_path(current_user.subscribes.where(:s_user_id => @user.id).take), method: "POST", role:"button", class: "btn btn-outline-danger"
    h4 style="padding:8px 0 0 0" О себе:
    p = @user.about

br

- @user.news.all.each do |news|
  = render partial: 'layouts/post', locals: {news: news}

app/views/user_profile/subscribes.html.slim
br
- if @subscr_cnt == 0
  p style="color:gray; text-align:center" Вы еще ни на кого не подписались
table style="max-widtsh:50%" class="table"
  /thead class="thead-dark"
    tr
      /th scope="col" Пользователь
      /th scope="col" Период рассылки в днях
      /th style="text-align:right" scope="col" Отписаться
  tbody
    - current_user.subscribes.all.order(created_at: :desc).each do |subscribe|
     tr
      /th scope="row"
      th scope="row" 
        - @s_user = User.find(subscribe.s_user_id)
        = image_tag @s_user.image.variant(resize: "64x64"), class: "rounded-circle d-inline" if @s_user.image.attached?
        h3 class="d-inline" = link_to @s_user.name, user_profile_path(@s_user), style: "padding:0 0 0 8px"
      / td
      /     = form_with(url: change_subscr_period_user_profile_path(subscribe), method:"post") do |f|
      /       div class="input-group mb-3"
      /         = f.text_field :period, value: subscribe.schedule_interval_days, class:"form-control", "aria-describedby":"button-addon2", style:"width:30px; max-width:50px"
      /         div class="input-group-append"
      /           = f.submit value:"Сохранить", class:"btn btn-outline-success", id:"button-addon2"
      td style="vertical-align:middle" align="right" = link_to "Отписаться", unsubscribe_user_profile_path(subscribe), method: :post, class:"btn btn-outline-danger", role:"button"
    td
    td align="right" = link_to "Отписаться от всех", user_profile_unsubscribe_all_path,  method: :post, class:"btn btn-outline-danger", role:"button" if @subscr_cnt > 0

app/views/user_profile/user_settings.html.slim
div style="max-width:50%"
 = form_with(url:user_profile_path(current_user), method:"put") do |f|
    label for="InputName" Имя
    div class="input-group mb-3" id="InputName"
     = f.text_field :name, placeholder: "Имя пользователя", class:"form-control", "aria-describedby":"button-addon2", value: current_user.name
    label for="InputName" Фамилия
    div class="input-group mb-3" id="InputLastName"
     = f.text_field :lastname, placeholder: "Фамилия", class:"form-control", "aria-describedby":"button-addon2", value: "#{current_user.lastname if current_user.lastname}"
    label for="InputEmail" Электронная почта
    div class="input-group mb-3" id="InputEmail"
     = f.text_field :email, placeholder: "Электронная почта", class:"form-control", "aria-describedby":"button-addon2", value: current_user.email
    label for="InputAbout" О себе
    div class="input-group mb-3" id="InputAbout"
     = f.text_area :about, placeholder: "Расскажите немного о себе", class:"form-control", "aria-describedby":"button-addon2", value: current_user.about, maxlength: "400"
    label for="FormGroupSelect" Настройка почтовой рассылки
    div class="input-group" id="FormGroupSelect"
        = f.select :mail_interval_id, options_for_select(mail_intervals, current_user.mail_interval.id), {}, {class: "form-control", id: "exampleFormControlSelect1"}        
        = f.select :subscribe_type_id, options_for_select(subscribe_types, current_user.subscribe_type.id), {}, {class: "form-control", id: "exampleFormControlSelect1"}
        div class="input-group-append"
            span class="input-group-text" Период
            span class="input-group-text" Тип
    br
    = f.submit value: "Сохранить", class: "btn btn-outline-success"
 = form_with(url:upload_file_user_profile_path(current_user), method:"post", id:"photo-form") do |f|
    br
      div#img-preview
        - if current_user.image.attached?
            = image_tag current_user.image.variant(resize: "250x250"), class:"img-thumbnail", id:"preview"
        - else
            = image_tag 'user_default.png', class:"img-thumbnail", style: "width:250px;heigth:250px", id:"preview"
    label for="ChosePicture" Выбрать изображение профиля
    div class="custom-file"
        = f.label :Изображения, class:"custom-file-label", for:"customFile", id:"filename"
        = f.file_field :image, class: "custom-file-input", id:"customFile", onchange:"fileInputChangeSingle(this, '250px', '250px', true)"
        = f.button :"Сохранить", class:"btn btn-outline-success", type: "button", onclick: "SendCropped(this)"