config/routes.rb
Rails.application.routes.draw do
  get 'news/favs', to: 'news#favs'
  devise_for :users
  resources :news do
    member do
      post :add_comment
      post :delete_comment
      post :like
      post :favorite_add
    end
  end
  resources :user_profile do
    member do
      post :change_subscr_period
      post :change_user_name
      post :change_user_email
      post :upload_file
      get :subscribe
      post :unsubscribe
      get :subscribes
      get :user_settings
      get :posts
    end
  end
  root to: 'news#index'
  post 'user_profile/unsubscribe_all', to: "user_profile#unsubscribe_all"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_post.html.slim
div class="jumbotron jumbotron-fluid rounded shadow-sm news-box"
  div class="container"
    div style="display:flex"
      h3 class="display-8" = link_to news.title, news
      = image_tag(news.user.image.variant(resize:"32x32"), :class=> "avatar", :style => "width:32px; height:32px;margin-left:auto;margin-right:5px;border-radius:50%") if news.user.image.attached?
      h3 class="display-8" style='#{"margin-left:auto" unless news.user.image.attached?}'
        - if news.user.id != current_user.id
          = link_to news.user.name, user_profile_path(news.user.id)
        - else
          = link_to news.user.name, user_profile_index_path
    p = time_ago_in_words(news.created_at)
    hr class="my-4"
    p class="lead" #{truncate news.text, length: 350} #{link_to 'Далее', news, style:"color:blue" if news.text.length > 350}
    div.btn-group role="group"
      = button_to like_news_path(news), form_class: "like-form" , class: "btn btn-outline-secondary btn-sm like-btn", remote: :true, style: "border:none", method: :post
        = image_tag("svg/heart-#{check_like(news) ? 'solid' : 'regular'}.svg", :class => 'svg-btn-icon', :"data-liked" => "false")
        span style="padding:0 0 0 5px;"
          = news.likes.count
      = button_to favorite_add_news_path(news), form_class: "favorite-form", class: "btn btn-outline-secondary btn-sm like-btn", style: "border:none", remote: :true, method: :post
        = image_tag("svg/star-#{check_favorite(news) ? 'solid' : 'regular'}.svg", :class => 'svg-btn-icon', :"data-favorite" => "false")

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | BlogRndSoft
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap&subset=cyrillic,cyrillic-ext,latin-ext" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Comfortaa:300,400,500,600,700&display=swap&subset=cyrillic,cyrillic-ext,latin-ext" rel="stylesheet">
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    div class="container"
      nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top shadow-sm" style="font-size:30px"
        = link_to "Rnd Soft Blog", root_path, class:"navbar-brand"
        button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
          span class="navbar-toggler-icon"
        - if user_signed_in?
          div class="collapse navbar-collapse" id="navbarSupportedContent"
            ul class="navbar-nav mr-auto" style="font-size:0.6em"
              li class="nav-item #{'active' if current_page?(:controller => 'news', :only_my => true)}"
                = link_to "Моя лента", news_index_path(only_my: :true), class: "nav-link"
              li class="nav-item #{'active' if current_page?(:controller => 'news', :action => 'favs')}"
                = link_to "Избранное", news_favs_path, class: "nav-link"
            div class="dropdown"
              a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" = current_user.name   
              div class="dropdown-menu" aria-labelledby="dropdownMenuLink"
                = link_to "Моя страница", user_profile_path(current_user), class:"dropdown-item"
                = link_to "Подписки", subscribes_user_profile_path(current_user), class:"dropdown-item"
                = link_to "Настройки", user_settings_user_profile_path(current_user), class:"dropdown-item"
                div class="dropdown-divider"
                = link_to "Выйти", destroy_user_session_path, method: :delete, class:"dropdown-item"
      - flash.each do |key, value|
          div role="alert" class="alert alert-#{notice_to_success(key.to_s)}"
            button type="button" class="close" data-dismiss="alert" aria-label="Close"
              span aria-hidden="true"  &times; 
            = value
      br
      = yield
    javascript:
     $(this).likeListnerOn();
     $(this).FavoriteListnerOn();